# Generated by Django 4.2.4 on 2023-09-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edital',
            options={'verbose_name_plural': 'Editais'},
        ),
        migrations.AlterField(
            model_name='edital',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('encerrado', 'Encerrado')], max_length=9),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
