# Generated by Django 4.2.4 on 2023-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0002_alter_edital_options_alter_edital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='inscricao',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
