# Generated by Django 4.2.4 on 2023-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0003_edital_inscricao_edital_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='site',
            new_name='endereco_digital',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='contato',
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
