# Generated by Django 4.2.5 on 2023-09-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0005_edital_imagem_alter_edital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='imagem',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/imagensEditais'),
        ),
    ]
