# Generated by Django 4.2.5 on 2023-09-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0012_alter_edital_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagem',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='logoEmpresas'),
        ),
    ]
