# Generated by Django 4.2.7 on 2023-11-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0013_alter_empresa_options_empresa_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
    ]
