# Generated by Django 4.2.7 on 2023-11-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0014_alter_empresa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='destaque',
            field=models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'nao')], max_length=3),
        ),
    ]
