# Generated by Django 4.2.7 on 2023-11-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0016_salvaremail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='salvarEmail',
            new_name='Email',
        ),
    ]
