# Generated by Django 4.2.7 on 2023-11-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0017_rename_salvaremail_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edital',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
