# Generated by Django 4.2.7 on 2023-12-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0018_rename_crated_at_edital_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='imagem',
            field=models.ImageField(blank=True, default='default.jpg', help_text='ATENÇÃO! Para uma melhor experiência do usuário, adicione apenas imagens png', null=True, upload_to='fotosEditais'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagem',
            field=models.ImageField(blank=True, default='default.jpg', help_text='ATENÇÃO! Para uma melhor experiência do usuário, adicione apenas imagens png', null=True, upload_to='logoEmpresas'),
        ),
    ]
