# Generated by Django 4.2.7 on 2024-03-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0021_alter_edital_destaque_alter_edital_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=600)),
            ],
        ),
    ]
