# Generated by Django 4.2.7 on 2024-03-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0024_alter_process_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Process',
            new_name='Procesos',
        ),
    ]
