# Generated by Django 4.2.7 on 2024-03-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0026_procesos_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procesos',
            new_name='Processos',
        ),
    ]
